services:
    lmdi.topicsearch.listener:
        class: lmdi\topicsearch\event\listener
        arguments:
            - '@template'
            - '@config'
            - '@user'
            - '@request'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
